DROP TABLE IF EXISTS `powerstation_event`;
DROP TABLE IF EXISTS `powerstation`;
DROP TABLE IF EXISTS `user`;

CREATE TABLE IF NOT EXISTS `user` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `powerstation` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NOT NULL,
  `capacity` DOUBLE NOT NULL,
  `user_id` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES user(`id`)
);

CREATE TABLE IF NOT EXISTS `powerstation_event` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ts` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `amount` DOUBLE NOT NULL,
  `powerstation_id` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`powerstation_id`) REFERENCES powerstation(`id`)
);
